name: make8bitart
version: master
summary: an in-browser canvas tool which is great fun!
description: |
  web-based pixel art application that's super fun and easy to use!

grade: stable
confinement: strict

apps:
  make8bitart:
    command: env TMPDIR=$XDG_RUNTIME_DIR desktop-launch $SNAP/app/make8bitart
    plugs:
      - home
      - x11
      - unity7
      - browser-support
      - network
      - gsettings
      - pulseaudio
      - opengl

parts:
  electron-app:
    source: app/
    plugin: nodejs
    stage-packages:
      - libnotify4
      - libappindicator1
      - libxtst6
      - libnss3
      - libxss1
      - fontconfig-config
      - gconf2
      - libasound2
      - pulseaudio
    after:
      - desktop-glib-only
    build: node_modules/.bin/electron-builder
    install: |
      mkdir $SNAPCRAFT_PART_INSTALL/app
      mv dist/linux-unpacked/* $SNAPCRAFT_PART_INSTALL/app
    prime:
      - -node_modules
